using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MvcStoreData.Infrastructure;
using System.Collections.Generic;

namespace MvcStoreData
{
    public class City
    {
        public int Id { get; set; }

        public int ProvinceId { get; set; }

        public string Name { get; set; }

        public virtual Province Province { get; set; }

        public virtual ICollection<UserAddress> UserAddresses { get; set; } = new HashSet<UserAddress>();
    }

    public class CityEntityTypeConfiguration : IEntityTypeConfiguration<City>
    {
        public void Configure(EntityTypeBuilder<City> builder)
        {

            builder
                .HasIndex(p => new { p.Name, p.ProvinceId })
                .IsUnique();

            builder
                .Property(p => p.Name)
                .IsRequired();

            builder
                .HasMany(p => p.UserAddresses)
                .WithOne(p => p.City)
                .HasForeignKey(p => p.CityId)
                .OnDelete(DeleteBehavior.Restrict);

            builder
                 .HasData(
            new City { Id = 1, ProvinceId = 1, Name = "Seyhan" },
            new City { Id = 2, ProvinceId = 1, Name = "Ceyhan" },
            new City { Id = 3, ProvinceId = 1, Name = "Feke" },
            new City { Id = 4, ProvinceId = 1, Name = "Karaisalı" },
            new City { Id = 5, ProvinceId = 1, Name = "Karataş" },
            new City { Id = 6, ProvinceId = 1, Name = "Kozan" },
            new City { Id = 7, ProvinceId = 1, Name = "Pozantı" },
            new City { Id = 8, ProvinceId = 1, Name = "Saimbeyli" },
            new City { Id = 9, ProvinceId = 1, Name = "Tufanbeyli" },
            new City { Id = 10, ProvinceId = 1, Name = "Yumurtalık" },
            new City { Id = 11, ProvinceId = 1, Name = "Yüreğir" },
            new City { Id = 12, ProvinceId = 1, Name = "Aladağ" },
            new City { Id = 13, ProvinceId = 1, Name = "İmamoğlu" },
            new City { Id = 14, ProvinceId = 1, Name = "Sarıçam" },
            new City { Id = 15, ProvinceId = 1, Name = "Çukurova" },
            new City { Id = 16, ProvinceId = 2, Name = "Adıyaman Merkez" },
            new City { Id = 17, ProvinceId = 2, Name = "Besni" },
            new City { Id = 18, ProvinceId = 2, Name = "Çelikhan" },
            new City { Id = 19, ProvinceId = 2, Name = "Gerger" },
            new City { Id = 20, ProvinceId = 2, Name = "Gölbaşı / Adıyaman" },
            new City { Id = 21, ProvinceId = 2, Name = "Kahta" },
            new City { Id = 22, ProvinceId = 2, Name = "Samsat" },
            new City { Id = 23, ProvinceId = 2, Name = "Sincik" },
            new City { Id = 24, ProvinceId = 2, Name = "Tut" },
            new City { Id = 25, ProvinceId = 3, Name = "Afyonkarahisar Merkez" },
            new City { Id = 26, ProvinceId = 3, Name = "Bolvadin" },
            new City { Id = 27, ProvinceId = 3, Name = "Çay" },
            new City { Id = 28, ProvinceId = 3, Name = "Dazkırı" },
            new City { Id = 29, ProvinceId = 3, Name = "Dinar" },
            new City { Id = 30, ProvinceId = 3, Name = "Emirdağ" },
            new City { Id = 31, ProvinceId = 3, Name = "İhsaniye" },
            new City { Id = 32, ProvinceId = 3, Name = "Sandıklı" },
            new City { Id = 33, ProvinceId = 3, Name = "Sinanpaşa" },
            new City { Id = 34, ProvinceId = 3, Name = "Sultandağı" },
            new City { Id = 35, ProvinceId = 3, Name = "Şuhut" },
            new City { Id = 36, ProvinceId = 3, Name = "Başmakçı" },
            new City { Id = 37, ProvinceId = 3, Name = "Bayat / Afyonkarahisar" },
            new City { Id = 38, ProvinceId = 3, Name = "İscehisar" },
            new City { Id = 39, ProvinceId = 3, Name = "Çobanlar" },
            new City { Id = 40, ProvinceId = 3, Name = "Evciler" },
            new City { Id = 41, ProvinceId = 3, Name = "Hocalar" },
            new City { Id = 42, ProvinceId = 3, Name = "Kızılören" },
            new City { Id = 43, ProvinceId = 4, Name = "Ağrı Merkez" },
            new City { Id = 44, ProvinceId = 4, Name = "Diyadin" },
            new City { Id = 45, ProvinceId = 4, Name = "Doğubayazıt" },
            new City { Id = 46, ProvinceId = 4, Name = "Eleşkirt" },
            new City { Id = 47, ProvinceId = 4, Name = "Hamur" },
            new City { Id = 48, ProvinceId = 4, Name = "Patnos" },
            new City { Id = 49, ProvinceId = 4, Name = "Taşlıçay" },
            new City { Id = 50, ProvinceId = 4, Name = "Tutak" },
            new City { Id = 51, ProvinceId = 5, Name = "Amasya Merkez" },
            new City { Id = 52, ProvinceId = 5, Name = "Göynücek" },
            new City { Id = 53, ProvinceId = 5, Name = "Gümüşhacıköy" },
            new City { Id = 54, ProvinceId = 5, Name = "Merzifon" },
            new City { Id = 55, ProvinceId = 5, Name = "Suluova" },
            new City { Id = 56, ProvinceId = 5, Name = "Taşova" },
            new City { Id = 57, ProvinceId = 5, Name = "Hamamözü" },
            new City { Id = 58, ProvinceId = 6, Name = "Altındağ" },
            new City { Id = 59, ProvinceId = 6, Name = "Ayaş" },
            new City { Id = 60, ProvinceId = 6, Name = "Bala" },
            new City { Id = 61, ProvinceId = 6, Name = "Beypazarı" },
            new City { Id = 62, ProvinceId = 6, Name = "Çamlıdere" },
            new City { Id = 63, ProvinceId = 6, Name = "Çankaya" },
            new City { Id = 64, ProvinceId = 6, Name = "Çubuk" },
            new City { Id = 65, ProvinceId = 6, Name = "Elmadağ" },
            new City { Id = 66, ProvinceId = 6, Name = "Güdül" },
            new City { Id = 67, ProvinceId = 6, Name = "Haymana" },
            new City { Id = 68, ProvinceId = 6, Name = "Kalecik" },
            new City { Id = 69, ProvinceId = 6, Name = "Kızılcahamam" },
            new City { Id = 70, ProvinceId = 6, Name = "Nallıhan" },
            new City { Id = 71, ProvinceId = 6, Name = "Polatlı" },
            new City { Id = 72, ProvinceId = 6, Name = "Şereflikoçhisar" },
            new City { Id = 73, ProvinceId = 6, Name = "Yenimahalle" },
            new City { Id = 74, ProvinceId = 6, Name = "Gölbaşı / Ankara" },
            new City { Id = 75, ProvinceId = 6, Name = "Keçiören" },
            new City { Id = 76, ProvinceId = 6, Name = "Mamak" },
            new City { Id = 77, ProvinceId = 6, Name = "Sincan" },
            new City { Id = 78, ProvinceId = 6, Name = "Kazan" },
            new City { Id = 79, ProvinceId = 6, Name = "Akyurt" },
            new City { Id = 80, ProvinceId = 6, Name = "Etimesgut" },
            new City { Id = 81, ProvinceId = 6, Name = "Evren" },
            new City { Id = 82, ProvinceId = 6, Name = "Pursaklar" },
            new City { Id = 83, ProvinceId = 7, Name = "Akseki" },
            new City { Id = 84, ProvinceId = 7, Name = "Alanya" },
            new City { Id = 85, ProvinceId = 7, Name = "Elmalı" },
            new City { Id = 86, ProvinceId = 7, Name = "Finike" },
            new City { Id = 87, ProvinceId = 7, Name = "Gazipaşa" },
            new City { Id = 88, ProvinceId = 7, Name = "Gündoğmuş" },
            new City { Id = 89, ProvinceId = 7, Name = "Kaş" },
            new City { Id = 90, ProvinceId = 7, Name = "Korkuteli" },
            new City { Id = 91, ProvinceId = 7, Name = "Kumluca" },
            new City { Id = 92, ProvinceId = 7, Name = "Manavgat" },
            new City { Id = 93, ProvinceId = 7, Name = "Serik" },
            new City { Id = 94, ProvinceId = 7, Name = "Demre" },
            new City { Id = 95, ProvinceId = 7, Name = "İbradı" },
            new City { Id = 96, ProvinceId = 7, Name = "Kemer / Antalya" },
            new City { Id = 97, ProvinceId = 7, Name = "Aksu / Antalya" },
            new City { Id = 98, ProvinceId = 7, Name = "Döşemealtı" },
            new City { Id = 99, ProvinceId = 7, Name = "Kepez" },
            new City { Id = 100, ProvinceId = 7, Name = "Konyaaltı" },
            new City { Id = 101, ProvinceId = 7, Name = "Muratpaşa" },
            new City { Id = 102, ProvinceId = 8, Name = "Ardanuç" },
            new City { Id = 103, ProvinceId = 8, Name = "Arhavi" },
            new City { Id = 104, ProvinceId = 8, Name = "Artvin Merkez" },
            new City { Id = 105, ProvinceId = 8, Name = "Borçka" },
            new City { Id = 106, ProvinceId = 8, Name = "Hopa" },
            new City { Id = 107, ProvinceId = 8, Name = "Şavşat" },
            new City { Id = 108, ProvinceId = 8, Name = "Yusufeli" },
            new City { Id = 109, ProvinceId = 8, Name = "Murgul" },
            new City { Id = 110, ProvinceId = 9, Name = "Bozdoğan" },
            new City { Id = 111, ProvinceId = 9, Name = "Çine" },
            new City { Id = 112, ProvinceId = 9, Name = "Germencik" },
            new City { Id = 113, ProvinceId = 9, Name = "Karacasu" },
            new City { Id = 114, ProvinceId = 9, Name = "Koçarlı" },
            new City { Id = 115, ProvinceId = 9, Name = "Kuşadası" },
            new City { Id = 116, ProvinceId = 9, Name = "Kuyucak" },
            new City { Id = 117, ProvinceId = 9, Name = "Nazilli" },
            new City { Id = 118, ProvinceId = 9, Name = "Söke" },
            new City { Id = 119, ProvinceId = 9, Name = "Sultanhisar" },
            new City { Id = 120, ProvinceId = 9, Name = "Yenipazar / Aydın" },
            new City { Id = 121, ProvinceId = 9, Name = "Buharkent" },
            new City { Id = 122, ProvinceId = 9, Name = "İncirliova" },
            new City { Id = 123, ProvinceId = 9, Name = "Karpuzlu" },
            new City { Id = 124, ProvinceId = 9, Name = "Köşk" },
            new City { Id = 125, ProvinceId = 9, Name = "Didim" },
            new City { Id = 126, ProvinceId = 9, Name = "Efeler" },
            new City { Id = 127, ProvinceId = 10, Name = "Ayvalık" },
            new City { Id = 128, ProvinceId = 10, Name = "Balya" },
            new City { Id = 129, ProvinceId = 10, Name = "Bandırma" },
            new City { Id = 130, ProvinceId = 10, Name = "Bigadiç" },
            new City { Id = 131, ProvinceId = 10, Name = "Burhaniye" },
            new City { Id = 132, ProvinceId = 10, Name = "Dursunbey" },
            new City { Id = 133, ProvinceId = 10, Name = "Edremit / Balıkesir" },
            new City { Id = 134, ProvinceId = 10, Name = "Erdek" },
            new City { Id = 135, ProvinceId = 10, Name = "Gönen / Balıkesir" },
            new City { Id = 136, ProvinceId = 10, Name = "Havran" },
            new City { Id = 137, ProvinceId = 10, Name = "İvrindi" },
            new City { Id = 138, ProvinceId = 10, Name = "Kepsut" },
            new City { Id = 139, ProvinceId = 10, Name = "Manyas" },
            new City { Id = 140, ProvinceId = 10, Name = "Savaştepe" },
            new City { Id = 141, ProvinceId = 10, Name = "Sındırgı" },
            new City { Id = 142, ProvinceId = 10, Name = "Susurluk" },
            new City { Id = 143, ProvinceId = 10, Name = "Marmara" },
            new City { Id = 144, ProvinceId = 10, Name = "Gömeç" },
            new City { Id = 145, ProvinceId = 10, Name = "Altıeylül" },
            new City { Id = 146, ProvinceId = 10, Name = "Karesi" },
            new City { Id = 147, ProvinceId = 11, Name = "Bilecik Merkez" },
            new City { Id = 148, ProvinceId = 11, Name = "Bozüyük" },
            new City { Id = 149, ProvinceId = 11, Name = "Gölpazarı" },
            new City { Id = 150, ProvinceId = 11, Name = "Osmaneli" },
            new City { Id = 151, ProvinceId = 11, Name = "Pazaryeri" },
            new City { Id = 152, ProvinceId = 11, Name = "Söğüt" },
            new City { Id = 153, ProvinceId = 11, Name = "Yenipazar / Bilecik" },
            new City { Id = 154, ProvinceId = 11, Name = "İnhisar" },
            new City { Id = 155, ProvinceId = 12, Name = "Bingöl Merkez" },
            new City { Id = 156, ProvinceId = 12, Name = "Genç" },
            new City { Id = 157, ProvinceId = 12, Name = "Karlıova" },
            new City { Id = 158, ProvinceId = 12, Name = "Kiğı" },
            new City { Id = 159, ProvinceId = 12, Name = "Solhan" },
            new City { Id = 160, ProvinceId = 12, Name = "Adaklı" },
            new City { Id = 161, ProvinceId = 12, Name = "Yayladere" },
            new City { Id = 162, ProvinceId = 12, Name = "Yedisu" },
            new City { Id = 163, ProvinceId = 13, Name = "Adilcevaz" },
            new City { Id = 164, ProvinceId = 13, Name = "Ahlat" },
            new City { Id = 165, ProvinceId = 13, Name = "Bitlis Merkez" },
            new City { Id = 166, ProvinceId = 13, Name = "Hizan" },
            new City { Id = 167, ProvinceId = 13, Name = "Mutki" },
            new City { Id = 168, ProvinceId = 13, Name = "Tatvan" },
            new City { Id = 169, ProvinceId = 13, Name = "Güroymak" },
            new City { Id = 170, ProvinceId = 14, Name = "Bolu Merkez" },
            new City { Id = 171, ProvinceId = 14, Name = "Gerede" },
            new City { Id = 172, ProvinceId = 14, Name = "Göynük" },
            new City { Id = 173, ProvinceId = 14, Name = "Kıbrıscık" },
            new City { Id = 174, ProvinceId = 14, Name = "Mengen" },
            new City { Id = 175, ProvinceId = 14, Name = "Mudurnu" },
            new City { Id = 176, ProvinceId = 14, Name = "Seben" },
            new City { Id = 177, ProvinceId = 14, Name = "Dörtdivan" },
            new City { Id = 178, ProvinceId = 14, Name = "Yeniçağa" },
            new City { Id = 179, ProvinceId = 15, Name = "Ağlasun" },
            new City { Id = 180, ProvinceId = 15, Name = "Bucak" },
            new City { Id = 181, ProvinceId = 15, Name = "Burdur Merkez" },
            new City { Id = 182, ProvinceId = 15, Name = "Gölhisar" },
            new City { Id = 183, ProvinceId = 15, Name = "Tefenni" },
            new City { Id = 184, ProvinceId = 15, Name = "Yeşilova" },
            new City { Id = 185, ProvinceId = 15, Name = "Karamanlı" },
            new City { Id = 186, ProvinceId = 15, Name = "Kemer / Burdur" },
            new City { Id = 187, ProvinceId = 15, Name = "Altınyayla / Burdur" },
            new City { Id = 188, ProvinceId = 15, Name = "Çavdır" },
            new City { Id = 189, ProvinceId = 15, Name = "Çeltikçi" },
            new City { Id = 190, ProvinceId = 16, Name = "Gemlik" },
            new City { Id = 191, ProvinceId = 16, Name = "İnegöl" },
            new City { Id = 192, ProvinceId = 16, Name = "İznik" },
            new City { Id = 193, ProvinceId = 16, Name = "Karacabey" },
            new City { Id = 194, ProvinceId = 16, Name = "Keles" },
            new City { Id = 195, ProvinceId = 16, Name = "Mudanya" },
            new City { Id = 196, ProvinceId = 16, Name = "Mustafakemalpaşa" },
            new City { Id = 197, ProvinceId = 16, Name = "Orhaneli" },
            new City { Id = 198, ProvinceId = 16, Name = "Orhangazi" },
            new City { Id = 199, ProvinceId = 16, Name = "Yenişehir / Bursa" },
            new City { Id = 200, ProvinceId = 16, Name = "Büyükorhan" },
            new City { Id = 201, ProvinceId = 16, Name = "Harmancık" },
            new City { Id = 202, ProvinceId = 16, Name = "Nilüfer" },
            new City { Id = 203, ProvinceId = 16, Name = "Osmangazi" },
            new City { Id = 204, ProvinceId = 16, Name = "Yıldırım" },
            new City { Id = 205, ProvinceId = 16, Name = "Gürsu" },
            new City { Id = 206, ProvinceId = 16, Name = "Kestel" },
            new City { Id = 207, ProvinceId = 17, Name = "Ayvacık / Çanakkale" },
            new City { Id = 208, ProvinceId = 17, Name = "Bayramiç" },
            new City { Id = 209, ProvinceId = 17, Name = "Biga" },
            new City { Id = 210, ProvinceId = 17, Name = "Bozcaada" },
            new City { Id = 211, ProvinceId = 17, Name = "Çan" },
            new City { Id = 212, ProvinceId = 17, Name = "Çanakkale Merkez" },
            new City { Id = 213, ProvinceId = 17, Name = "Eceabat" },
            new City { Id = 214, ProvinceId = 17, Name = "Ezine" },
            new City { Id = 215, ProvinceId = 17, Name = "Gelibolu" },
            new City { Id = 216, ProvinceId = 17, Name = "Gökçeada" },
            new City { Id = 217, ProvinceId = 17, Name = "Lapseki" },
            new City { Id = 218, ProvinceId = 17, Name = "Yenice / Çanakkale" },
            new City { Id = 219, ProvinceId = 18, Name = "Çankırı Merkez" },
            new City { Id = 220, ProvinceId = 18, Name = "Çerkeş" },
            new City { Id = 221, ProvinceId = 18, Name = "Eldivan" },
            new City { Id = 222, ProvinceId = 18, Name = "Ilgaz" },
            new City { Id = 223, ProvinceId = 18, Name = "Kurşunlu" },
            new City { Id = 224, ProvinceId = 18, Name = "Orta" },
            new City { Id = 225, ProvinceId = 18, Name = "Şabanözü" },
            new City { Id = 226, ProvinceId = 18, Name = "Yapraklı" },
            new City { Id = 227, ProvinceId = 18, Name = "Atkaracalar" },
            new City { Id = 228, ProvinceId = 18, Name = "Kızılırmak" },
            new City { Id = 229, ProvinceId = 18, Name = "Bayramören" },
            new City { Id = 230, ProvinceId = 18, Name = "Korgun" },
            new City { Id = 231, ProvinceId = 19, Name = "Alaca" },
            new City { Id = 232, ProvinceId = 19, Name = "Bayat / Çorum" },
            new City { Id = 233, ProvinceId = 19, Name = "Çorum Merkez" },
            new City { Id = 234, ProvinceId = 19, Name = "İskilip" },
            new City { Id = 235, ProvinceId = 19, Name = "Kargı" },
            new City { Id = 236, ProvinceId = 19, Name = "Mecitözü" },
            new City { Id = 237, ProvinceId = 19, Name = "Ortaköy / Çorum" },
            new City { Id = 238, ProvinceId = 19, Name = "Osmancık" },
            new City { Id = 239, ProvinceId = 19, Name = "Sungurlu" },
            new City { Id = 240, ProvinceId = 19, Name = "Boğazkale" },
            new City { Id = 241, ProvinceId = 19, Name = "Uğurludağ" },
            new City { Id = 242, ProvinceId = 19, Name = "Dodurga" },
            new City { Id = 243, ProvinceId = 19, Name = "Laçin" },
            new City { Id = 244, ProvinceId = 19, Name = "Oğuzlar" },
            new City { Id = 245, ProvinceId = 20, Name = "Acıpayam" },
            new City { Id = 246, ProvinceId = 20, Name = "Buldan" },
            new City { Id = 247, ProvinceId = 20, Name = "Çal" },
            new City { Id = 248, ProvinceId = 20, Name = "Çameli" },
            new City { Id = 249, ProvinceId = 20, Name = "Çardak" },
            new City { Id = 250, ProvinceId = 20, Name = "Çivril" },
            new City { Id = 251, ProvinceId = 20, Name = "Güney" },
            new City { Id = 252, ProvinceId = 20, Name = "Kale / Denizli" },
            new City { Id = 253, ProvinceId = 20, Name = "Sarayköy" },
            new City { Id = 254, ProvinceId = 20, Name = "Tavas" },
            new City { Id = 255, ProvinceId = 20, Name = "Babadağ" },
            new City { Id = 256, ProvinceId = 20, Name = "Bekilli" },
            new City { Id = 257, ProvinceId = 20, Name = "Honaz" },
            new City { Id = 258, ProvinceId = 20, Name = "Serinhisar" },
            new City { Id = 259, ProvinceId = 20, Name = "Pamukkale" },
            new City { Id = 260, ProvinceId = 20, Name = "Baklan" },
            new City { Id = 261, ProvinceId = 20, Name = "Beyağaç" },
            new City { Id = 262, ProvinceId = 20, Name = "Bozkurt / Denizli" },
            new City { Id = 263, ProvinceId = 20, Name = "Merkezefendi" },
            new City { Id = 264, ProvinceId = 21, Name = "Bismil" },
            new City { Id = 265, ProvinceId = 21, Name = "Çermik" },
            new City { Id = 266, ProvinceId = 21, Name = "Çınar" },
            new City { Id = 267, ProvinceId = 21, Name = "Çüngüş" },
            new City { Id = 268, ProvinceId = 21, Name = "Dicle" },
            new City { Id = 269, ProvinceId = 21, Name = "Ergani" },
            new City { Id = 270, ProvinceId = 21, Name = "Hani" },
            new City { Id = 271, ProvinceId = 21, Name = "Hazro" },
            new City { Id = 272, ProvinceId = 21, Name = "Kulp" },
            new City { Id = 273, ProvinceId = 21, Name = "Lice" },
            new City { Id = 274, ProvinceId = 21, Name = "Silvan" },
            new City { Id = 275, ProvinceId = 21, Name = "Eğil" },
            new City { Id = 276, ProvinceId = 21, Name = "Kocaköy" },
            new City { Id = 277, ProvinceId = 21, Name = "Bağlar" },
            new City { Id = 278, ProvinceId = 21, Name = "Kayapınar" },
            new City { Id = 279, ProvinceId = 21, Name = "Sur" },
            new City { Id = 280, ProvinceId = 21, Name = "Yenişehir / Diyarbakır" },
            new City { Id = 281, ProvinceId = 22, Name = "Edirne Merkez" },
            new City { Id = 282, ProvinceId = 22, Name = "Enez" },
            new City { Id = 283, ProvinceId = 22, Name = "Havsa" },
            new City { Id = 284, ProvinceId = 22, Name = "İpsala" },
            new City { Id = 285, ProvinceId = 22, Name = "Keşan" },
            new City { Id = 286, ProvinceId = 22, Name = "Lalapaşa" },
            new City { Id = 287, ProvinceId = 22, Name = "Meriç" },
            new City { Id = 288, ProvinceId = 22, Name = "Uzunköprü" },
            new City { Id = 289, ProvinceId = 22, Name = "Süloğlu" },
            new City { Id = 290, ProvinceId = 23, Name = "Ağın" },
            new City { Id = 291, ProvinceId = 23, Name = "Baskil" },
            new City { Id = 292, ProvinceId = 23, Name = "Elazığ Merkez" },
            new City { Id = 293, ProvinceId = 23, Name = "Karakoçan" },
            new City { Id = 294, ProvinceId = 23, Name = "Keban" },
            new City { Id = 295, ProvinceId = 23, Name = "Maden" },
            new City { Id = 296, ProvinceId = 23, Name = "Palu" },
            new City { Id = 297, ProvinceId = 23, Name = "Sivrice" },
            new City { Id = 298, ProvinceId = 23, Name = "Arıcak" },
            new City { Id = 299, ProvinceId = 23, Name = "Kovancılar" },
            new City { Id = 300, ProvinceId = 23, Name = "Alacakaya" },
            new City { Id = 301, ProvinceId = 24, Name = "Çayırlı" },
            new City { Id = 302, ProvinceId = 24, Name = "Erzincan Merkez" },
            new City { Id = 303, ProvinceId = 24, Name = "İliç" },
            new City { Id = 304, ProvinceId = 24, Name = "Kemah" },
            new City { Id = 305, ProvinceId = 24, Name = "Kemaliye" },
            new City { Id = 306, ProvinceId = 24, Name = "Refahiye" },
            new City { Id = 307, ProvinceId = 24, Name = "Tercan" },
            new City { Id = 308, ProvinceId = 24, Name = "Üzümlü" },
            new City { Id = 309, ProvinceId = 24, Name = "Otlukbeli" },
            new City { Id = 310, ProvinceId = 25, Name = "Aşkale" },
            new City { Id = 311, ProvinceId = 25, Name = "Çat" },
            new City { Id = 312, ProvinceId = 25, Name = "Hınıs" },
            new City { Id = 313, ProvinceId = 25, Name = "Horasan" },
            new City { Id = 314, ProvinceId = 25, Name = "İspir" },
            new City { Id = 315, ProvinceId = 25, Name = "Karayazı" },
            new City { Id = 316, ProvinceId = 25, Name = "Narman" },
            new City { Id = 317, ProvinceId = 25, Name = "Oltu" },
            new City { Id = 318, ProvinceId = 25, Name = "Olur" },
            new City { Id = 319, ProvinceId = 25, Name = "Pasinler" },
            new City { Id = 320, ProvinceId = 25, Name = "Şenkaya" },
            new City { Id = 321, ProvinceId = 25, Name = "Tekman" },
            new City { Id = 322, ProvinceId = 25, Name = "Tortum" },
            new City { Id = 323, ProvinceId = 25, Name = "Karaçoban" },
            new City { Id = 324, ProvinceId = 25, Name = "Uzundere" },
            new City { Id = 325, ProvinceId = 25, Name = "Pazaryolu" },
            new City { Id = 326, ProvinceId = 25, Name = "Aziziye" },
            new City { Id = 327, ProvinceId = 25, Name = "Köprüköy" },
            new City { Id = 328, ProvinceId = 25, Name = "Palandöken" },
            new City { Id = 329, ProvinceId = 25, Name = "Yakutiye" },
            new City { Id = 330, ProvinceId = 26, Name = "Çifteler" },
            new City { Id = 331, ProvinceId = 26, Name = "Mahmudiye" },
            new City { Id = 332, ProvinceId = 26, Name = "Mihalıççık" },
            new City { Id = 333, ProvinceId = 26, Name = "Sarıcakaya" },
            new City { Id = 334, ProvinceId = 26, Name = "Seyitgazi" },
            new City { Id = 335, ProvinceId = 26, Name = "Sivrihisar" },
            new City { Id = 336, ProvinceId = 26, Name = "Alpu" },
            new City { Id = 337, ProvinceId = 26, Name = "Beylikova" },
            new City { Id = 338, ProvinceId = 26, Name = "İnönü" },
            new City { Id = 339, ProvinceId = 26, Name = "Günyüzü" },
            new City { Id = 340, ProvinceId = 26, Name = "Han" },
            new City { Id = 341, ProvinceId = 26, Name = "Mihalgazi" },
            new City { Id = 342, ProvinceId = 26, Name = "Odunpazarı" },
            new City { Id = 343, ProvinceId = 26, Name = "Tepebaşı" },
            new City { Id = 344, ProvinceId = 27, Name = "Araban" },
            new City { Id = 345, ProvinceId = 27, Name = "İslahiye" },
            new City { Id = 346, ProvinceId = 27, Name = "Nizip" },
            new City { Id = 347, ProvinceId = 27, Name = "Oğuzeli" },
            new City { Id = 348, ProvinceId = 27, Name = "Yavuzeli" },
            new City { Id = 349, ProvinceId = 27, Name = "Şahinbey" },
            new City { Id = 350, ProvinceId = 27, Name = "Şehitkamil" },
            new City { Id = 351, ProvinceId = 27, Name = "Karkamış" },
            new City { Id = 352, ProvinceId = 27, Name = "Nurdağı" },
            new City { Id = 353, ProvinceId = 28, Name = "Alucra" },
            new City { Id = 354, ProvinceId = 28, Name = "Bulancak" },
            new City { Id = 355, ProvinceId = 28, Name = "Dereli" },
            new City { Id = 356, ProvinceId = 28, Name = "Espiye" },
            new City { Id = 357, ProvinceId = 28, Name = "Eynesil" },
            new City { Id = 358, ProvinceId = 28, Name = "Giresun Merkez" },
            new City { Id = 359, ProvinceId = 28, Name = "Görele" },
            new City { Id = 360, ProvinceId = 28, Name = "Keşap" },
            new City { Id = 361, ProvinceId = 28, Name = "Şebinkarahisar" },
            new City { Id = 362, ProvinceId = 28, Name = "Tirebolu" },
            new City { Id = 363, ProvinceId = 28, Name = "Piraziz" },
            new City { Id = 364, ProvinceId = 28, Name = "Yağlıdere" },
            new City { Id = 365, ProvinceId = 28, Name = "Çamoluk" },
            new City { Id = 366, ProvinceId = 28, Name = "Çanakçı" },
            new City { Id = 367, ProvinceId = 28, Name = "Doğankent" },
            new City { Id = 368, ProvinceId = 28, Name = "Güce" },
            new City { Id = 369, ProvinceId = 29, Name = "Gümüşhane Merkez" },
            new City { Id = 370, ProvinceId = 29, Name = "Kelkit" },
            new City { Id = 371, ProvinceId = 29, Name = "Şiran" },
            new City { Id = 372, ProvinceId = 29, Name = "Torul" },
            new City { Id = 373, ProvinceId = 29, Name = "Köse" },
            new City { Id = 374, ProvinceId = 29, Name = "Kürtün" },
            new City { Id = 375, ProvinceId = 30, Name = "Çukurca" },
            new City { Id = 376, ProvinceId = 30, Name = "Hakkari Merkez" },
            new City { Id = 377, ProvinceId = 30, Name = "Şemdinli" },
            new City { Id = 378, ProvinceId = 30, Name = "Yüksekova" },
            new City { Id = 379, ProvinceId = 31, Name = "Altınözü" },
            new City { Id = 380, ProvinceId = 31, Name = "Dörtyol" },
            new City { Id = 381, ProvinceId = 31, Name = "Hassa" },
            new City { Id = 382, ProvinceId = 31, Name = "İskenderun" },
            new City { Id = 383, ProvinceId = 31, Name = "Kırıkhan" },
            new City { Id = 384, ProvinceId = 31, Name = "Reyhanlı" },
            new City { Id = 385, ProvinceId = 31, Name = "Samandağ" },
            new City { Id = 386, ProvinceId = 31, Name = "Yayladağı" },
            new City { Id = 387, ProvinceId = 31, Name = "Erzin" },
            new City { Id = 388, ProvinceId = 31, Name = "Belen" },
            new City { Id = 389, ProvinceId = 31, Name = "Kumlu" },
            new City { Id = 390, ProvinceId = 31, Name = "Antakya" },
            new City { Id = 391, ProvinceId = 31, Name = "Arsuz" },
            new City { Id = 392, ProvinceId = 31, Name = "Defne" },
            new City { Id = 393, ProvinceId = 31, Name = "Payas" },
            new City { Id = 394, ProvinceId = 32, Name = "Atabey" },
            new City { Id = 395, ProvinceId = 32, Name = "Eğirdir" },
            new City { Id = 396, ProvinceId = 32, Name = "Gelendost" },
            new City { Id = 397, ProvinceId = 32, Name = "Isparta Merkez" },
            new City { Id = 398, ProvinceId = 32, Name = "Keçiborlu" },
            new City { Id = 399, ProvinceId = 32, Name = "Senirkent" },
            new City { Id = 400, ProvinceId = 32, Name = "Sütçüler" },
            new City { Id = 401, ProvinceId = 32, Name = "Şarkikaraağaç" },
            new City { Id = 402, ProvinceId = 32, Name = "Uluborlu" },
            new City { Id = 403, ProvinceId = 32, Name = "Yalvaç" },
            new City { Id = 404, ProvinceId = 32, Name = "Aksu / Isparta" },
            new City { Id = 405, ProvinceId = 32, Name = "Gönen / Isparta" },
            new City { Id = 406, ProvinceId = 32, Name = "Yenişarbademli" },
            new City { Id = 407, ProvinceId = 33, Name = "Anamur" },
            new City { Id = 408, ProvinceId = 33, Name = "Erdemli" },
            new City { Id = 409, ProvinceId = 33, Name = "Gülnar" },
            new City { Id = 410, ProvinceId = 33, Name = "Mut" },
            new City { Id = 411, ProvinceId = 33, Name = "Silifke" },
            new City { Id = 412, ProvinceId = 33, Name = "Tarsus" },
            new City { Id = 413, ProvinceId = 33, Name = "Aydıncık / Mersin" },
            new City { Id = 414, ProvinceId = 33, Name = "Bozyazı" },
            new City { Id = 415, ProvinceId = 33, Name = "Çamlıyayla" },
            new City { Id = 416, ProvinceId = 33, Name = "Akdeniz" },
            new City { Id = 417, ProvinceId = 33, Name = "Mezitli" },
            new City { Id = 418, ProvinceId = 33, Name = "Toroslar" },
            new City { Id = 419, ProvinceId = 33, Name = "Yenişehir / Mersin" },
            new City { Id = 420, ProvinceId = 34, Name = "Adalar" },
            new City { Id = 421, ProvinceId = 34, Name = "Bakırköy" },
            new City { Id = 422, ProvinceId = 34, Name = "Beşiktaş" },
            new City { Id = 423, ProvinceId = 34, Name = "Beykoz" },
            new City { Id = 424, ProvinceId = 34, Name = "Beyoğlu" },
            new City { Id = 425, ProvinceId = 34, Name = "Çatalca" },
            new City { Id = 426, ProvinceId = 34, Name = "Eyüp" },
            new City { Id = 427, ProvinceId = 34, Name = "Fatih" },
            new City { Id = 428, ProvinceId = 34, Name = "Gaziosmanpaşa" },
            new City { Id = 429, ProvinceId = 34, Name = "Kadıköy" },
            new City { Id = 430, ProvinceId = 34, Name = "Kartal" },
            new City { Id = 431, ProvinceId = 34, Name = "Sarıyer" },
            new City { Id = 432, ProvinceId = 34, Name = "Silivri" },
            new City { Id = 433, ProvinceId = 34, Name = "Şile" },
            new City { Id = 434, ProvinceId = 34, Name = "Şişli" },
            new City { Id = 435, ProvinceId = 34, Name = "Üsküdar" },
            new City { Id = 436, ProvinceId = 34, Name = "Zeytinburnu" },
            new City { Id = 437, ProvinceId = 34, Name = "Büyükçekmece" },
            new City { Id = 438, ProvinceId = 34, Name = "Kağıthane" },
            new City { Id = 439, ProvinceId = 34, Name = "Küçükçekmece" },
            new City { Id = 440, ProvinceId = 34, Name = "Pendik" },
            new City { Id = 441, ProvinceId = 34, Name = "Ümraniye" },
            new City { Id = 442, ProvinceId = 34, Name = "Bayrampaşa" },
            new City { Id = 443, ProvinceId = 34, Name = "Avcılar" },
            new City { Id = 444, ProvinceId = 34, Name = "Bağcılar" },
            new City { Id = 445, ProvinceId = 34, Name = "Bahçelievler" },
            new City { Id = 446, ProvinceId = 34, Name = "Güngören" },
            new City { Id = 447, ProvinceId = 34, Name = "Maltepe" },
            new City { Id = 448, ProvinceId = 34, Name = "Sultanbeyli" },
            new City { Id = 449, ProvinceId = 34, Name = "Tuzla" },
            new City { Id = 450, ProvinceId = 34, Name = "Esenler" },
            new City { Id = 451, ProvinceId = 34, Name = "Arnavutköy" },
            new City { Id = 452, ProvinceId = 34, Name = "Ataşehir" },
            new City { Id = 453, ProvinceId = 34, Name = "Başakşehir" },
            new City { Id = 454, ProvinceId = 34, Name = "Beylikdüzü" },
            new City { Id = 455, ProvinceId = 34, Name = "Çekmeköy" },
            new City { Id = 456, ProvinceId = 34, Name = "Esenyurt" },
            new City { Id = 457, ProvinceId = 34, Name = "Sancaktepe" },
            new City { Id = 458, ProvinceId = 34, Name = "Sultangazi" },
            new City { Id = 459, ProvinceId = 35, Name = "Aliağa" },
            new City { Id = 460, ProvinceId = 35, Name = "Bayındır" },
            new City { Id = 461, ProvinceId = 35, Name = "Bergama" },
            new City { Id = 462, ProvinceId = 35, Name = "Bornova" },
            new City { Id = 463, ProvinceId = 35, Name = "Çeşme" },
            new City { Id = 464, ProvinceId = 35, Name = "Dikili" },
            new City { Id = 465, ProvinceId = 35, Name = "Foça" },
            new City { Id = 466, ProvinceId = 35, Name = "Karaburun" },
            new City { Id = 467, ProvinceId = 35, Name = "Karşıyaka" },
            new City { Id = 468, ProvinceId = 35, Name = "Kemalpaşa / İzmir" },
            new City { Id = 469, ProvinceId = 35, Name = "Kınık" },
            new City { Id = 470, ProvinceId = 35, Name = "Kiraz" },
            new City { Id = 471, ProvinceId = 35, Name = "Menemen" },
            new City { Id = 472, ProvinceId = 35, Name = "Ödemiş" },
            new City { Id = 473, ProvinceId = 35, Name = "Seferihisar" },
            new City { Id = 474, ProvinceId = 35, Name = "Selçuk" },
            new City { Id = 475, ProvinceId = 35, Name = "Tire" },
            new City { Id = 476, ProvinceId = 35, Name = "Torbalı" },
            new City { Id = 477, ProvinceId = 35, Name = "Urla" },
            new City { Id = 478, ProvinceId = 35, Name = "Beydağ" },
            new City { Id = 479, ProvinceId = 35, Name = "Buca" },
            new City { Id = 480, ProvinceId = 35, Name = "Konak" },
            new City { Id = 481, ProvinceId = 35, Name = "Menderes" },
            new City { Id = 482, ProvinceId = 35, Name = "Balçova" },
            new City { Id = 483, ProvinceId = 35, Name = "Çiğli" },
            new City { Id = 484, ProvinceId = 35, Name = "Gaziemir" },
            new City { Id = 485, ProvinceId = 35, Name = "Narlıdere" },
            new City { Id = 486, ProvinceId = 35, Name = "Güzelbahçe" },
            new City { Id = 487, ProvinceId = 35, Name = "Bayraklı" },
            new City { Id = 488, ProvinceId = 35, Name = "Karabağlar" },
            new City { Id = 489, ProvinceId = 36, Name = "Arpaçay" },
            new City { Id = 490, ProvinceId = 36, Name = "Digor" },
            new City { Id = 491, ProvinceId = 36, Name = "Kağızman" },
            new City { Id = 492, ProvinceId = 36, Name = "Kars Merkez" },
            new City { Id = 493, ProvinceId = 36, Name = "Sarıkamış" },
            new City { Id = 494, ProvinceId = 36, Name = "Selim" },
            new City { Id = 495, ProvinceId = 36, Name = "Susuz" },
            new City { Id = 496, ProvinceId = 36, Name = "Akyaka" },
            new City { Id = 497, ProvinceId = 37, Name = "Abana" },
            new City { Id = 498, ProvinceId = 37, Name = "Araç" },
            new City { Id = 499, ProvinceId = 37, Name = "Azdavay" },
            new City { Id = 500, ProvinceId = 37, Name = "Bozkurt / Kastamonu" },
            new City { Id = 501, ProvinceId = 37, Name = "Cide" },
            new City { Id = 502, ProvinceId = 37, Name = "Çatalzeytin" },
            new City { Id = 503, ProvinceId = 37, Name = "Daday" },
            new City { Id = 504, ProvinceId = 37, Name = "Devrekani" },
            new City { Id = 505, ProvinceId = 37, Name = "İnebolu" },
            new City { Id = 506, ProvinceId = 37, Name = "Kastamonu Merkez" },
            new City { Id = 507, ProvinceId = 37, Name = "Küre" },
            new City { Id = 508, ProvinceId = 37, Name = "Taşköprü" },
            new City { Id = 509, ProvinceId = 37, Name = "Tosya" },
            new City { Id = 510, ProvinceId = 37, Name = "İhsangazi" },
            new City { Id = 511, ProvinceId = 37, Name = "Pınarbaşı / Kastamonu" },
            new City { Id = 512, ProvinceId = 37, Name = "Şenpazar" },
            new City { Id = 513, ProvinceId = 37, Name = "Ağlı" },
            new City { Id = 514, ProvinceId = 37, Name = "Doğanyurt" },
            new City { Id = 515, ProvinceId = 37, Name = "Hanönü" },
            new City { Id = 516, ProvinceId = 37, Name = "Seydiler" },
            new City { Id = 517, ProvinceId = 38, Name = "Bünyan" },
            new City { Id = 518, ProvinceId = 38, Name = "Develi" },
            new City { Id = 519, ProvinceId = 38, Name = "Felahiye" },
            new City { Id = 520, ProvinceId = 38, Name = "İncesu" },
            new City { Id = 521, ProvinceId = 38, Name = "Pınarbaşı / Kayseri" },
            new City { Id = 522, ProvinceId = 38, Name = "Sarıoğlan" },
            new City { Id = 523, ProvinceId = 38, Name = "Sarız" },
            new City { Id = 524, ProvinceId = 38, Name = "Tomarza" },
            new City { Id = 525, ProvinceId = 38, Name = "Yahyalı" },
            new City { Id = 526, ProvinceId = 38, Name = "Yeşilhisar" },
            new City { Id = 527, ProvinceId = 38, Name = "Akkışla" },
            new City { Id = 528, ProvinceId = 38, Name = "Talas" },
            new City { Id = 529, ProvinceId = 38, Name = "Kocasinan" },
            new City { Id = 530, ProvinceId = 38, Name = "Melikgazi" },
            new City { Id = 531, ProvinceId = 38, Name = "Hacılar" },
            new City { Id = 532, ProvinceId = 38, Name = "Özvatan" },
            new City { Id = 533, ProvinceId = 39, Name = "Babaeski" },
            new City { Id = 534, ProvinceId = 39, Name = "Demirköy" },
            new City { Id = 535, ProvinceId = 39, Name = "Kırklareli Merkez" },
            new City { Id = 536, ProvinceId = 39, Name = "Kofçaz" },
            new City { Id = 537, ProvinceId = 39, Name = "Lüleburgaz" },
            new City { Id = 538, ProvinceId = 39, Name = "Pehlivanköy" },
            new City { Id = 539, ProvinceId = 39, Name = "Pınarhisar" },
            new City { Id = 540, ProvinceId = 39, Name = "Vize" },
            new City { Id = 541, ProvinceId = 40, Name = "Çiçekdağı" },
            new City { Id = 542, ProvinceId = 40, Name = "Kaman" },
            new City { Id = 543, ProvinceId = 40, Name = "Kırşehir Merkez" },
            new City { Id = 544, ProvinceId = 40, Name = "Mucur" },
            new City { Id = 545, ProvinceId = 40, Name = "Akpınar" },
            new City { Id = 546, ProvinceId = 40, Name = "Akçakent" },
            new City { Id = 547, ProvinceId = 40, Name = "Boztepe" },
            new City { Id = 548, ProvinceId = 41, Name = "Gebze" },
            new City { Id = 549, ProvinceId = 41, Name = "Gölcük" },
            new City { Id = 550, ProvinceId = 41, Name = "Kandıra" },
            new City { Id = 551, ProvinceId = 41, Name = "Karamürsel" },
            new City { Id = 552, ProvinceId = 41, Name = "Körfez" },
            new City { Id = 553, ProvinceId = 41, Name = "Derince" },
            new City { Id = 554, ProvinceId = 41, Name = "Başiskele" },
            new City { Id = 555, ProvinceId = 41, Name = "Çayırova" },
            new City { Id = 556, ProvinceId = 41, Name = "Darıca" },
            new City { Id = 557, ProvinceId = 41, Name = "Dilovası" },
            new City { Id = 558, ProvinceId = 41, Name = "İzmit" },
            new City { Id = 559, ProvinceId = 41, Name = "Kartepe" },
            new City { Id = 560, ProvinceId = 42, Name = "Akşehir" },
            new City { Id = 561, ProvinceId = 42, Name = "Beyşehir" },
            new City { Id = 562, ProvinceId = 42, Name = "Bozkır" },
            new City { Id = 563, ProvinceId = 42, Name = "Cihanbeyli" },
            new City { Id = 564, ProvinceId = 42, Name = "Çumra" },
            new City { Id = 565, ProvinceId = 42, Name = "Doğanhisar" },
            new City { Id = 566, ProvinceId = 42, Name = "Ereğli / Konya" },
            new City { Id = 567, ProvinceId = 42, Name = "Hadim" },
            new City { Id = 568, ProvinceId = 42, Name = "Ilgın" },
            new City { Id = 569, ProvinceId = 42, Name = "Kadınhanı" },
            new City { Id = 570, ProvinceId = 42, Name = "Karapınar" },
            new City { Id = 571, ProvinceId = 42, Name = "Kulu" },
            new City { Id = 572, ProvinceId = 42, Name = "Sarayönü" },
            new City { Id = 573, ProvinceId = 42, Name = "Seydişehir" },
            new City { Id = 574, ProvinceId = 42, Name = "Yunak" },
            new City { Id = 575, ProvinceId = 42, Name = "Akören" },
            new City { Id = 576, ProvinceId = 42, Name = "Altınekin" },
            new City { Id = 577, ProvinceId = 42, Name = "Derebucak" },
            new City { Id = 578, ProvinceId = 42, Name = "Hüyük" },
            new City { Id = 579, ProvinceId = 42, Name = "Karatay" },
            new City { Id = 580, ProvinceId = 42, Name = "Meram" },
            new City { Id = 581, ProvinceId = 42, Name = "Selçuklu" },
            new City { Id = 582, ProvinceId = 42, Name = "Taşkent" },
            new City { Id = 583, ProvinceId = 42, Name = "Ahırlı" },
            new City { Id = 584, ProvinceId = 42, Name = "Çeltik" },
            new City { Id = 585, ProvinceId = 42, Name = "Derbent" },
            new City { Id = 586, ProvinceId = 42, Name = "Emirgazi" },
            new City { Id = 587, ProvinceId = 42, Name = "Güneysınır" },
            new City { Id = 588, ProvinceId = 42, Name = "Halkapınar" },
            new City { Id = 589, ProvinceId = 42, Name = "Tuzlukçu" },
            new City { Id = 590, ProvinceId = 42, Name = "Yalıhüyük" },
            new City { Id = 591, ProvinceId = 43, Name = "Altıntaş" },
            new City { Id = 592, ProvinceId = 43, Name = "Domaniç" },
            new City { Id = 593, ProvinceId = 43, Name = "Emet" },
            new City { Id = 594, ProvinceId = 43, Name = "Gediz" },
            new City { Id = 595, ProvinceId = 43, Name = "Kütahya Merkez" },
            new City { Id = 596, ProvinceId = 43, Name = "Simav" },
            new City { Id = 597, ProvinceId = 43, Name = "Tavşanlı" },
            new City { Id = 598, ProvinceId = 43, Name = "Aslanapa" },
            new City { Id = 599, ProvinceId = 43, Name = "Dumlupınar" },
            new City { Id = 600, ProvinceId = 43, Name = "Hisarcık" },
            new City { Id = 601, ProvinceId = 43, Name = "Şaphane" },
            new City { Id = 602, ProvinceId = 43, Name = "Çavdarhisar" },
            new City { Id = 603, ProvinceId = 43, Name = "Pazarlar" },
            new City { Id = 604, ProvinceId = 44, Name = "Akçadağ" },
            new City { Id = 605, ProvinceId = 44, Name = "Arapgir" },
            new City { Id = 606, ProvinceId = 44, Name = "Arguvan" },
            new City { Id = 607, ProvinceId = 44, Name = "Darende" },
            new City { Id = 608, ProvinceId = 44, Name = "Doğanşehir" },
            new City { Id = 609, ProvinceId = 44, Name = "Hekimhan" },
            new City { Id = 610, ProvinceId = 44, Name = "Pütürge" },
            new City { Id = 611, ProvinceId = 44, Name = "Yeşilyurt / Malatya" },
            new City { Id = 612, ProvinceId = 44, Name = "Battalgazi" },
            new City { Id = 613, ProvinceId = 44, Name = "Doğanyol" },
            new City { Id = 614, ProvinceId = 44, Name = "Kale / Malatya" },
            new City { Id = 615, ProvinceId = 44, Name = "Kuluncak" },
            new City { Id = 616, ProvinceId = 44, Name = "Yazıhan" },
            new City { Id = 617, ProvinceId = 45, Name = "Akhisar" },
            new City { Id = 618, ProvinceId = 45, Name = "Alaşehir" },
            new City { Id = 619, ProvinceId = 45, Name = "Demirci" },
            new City { Id = 620, ProvinceId = 45, Name = "Gördes" },
            new City { Id = 621, ProvinceId = 45, Name = "Kırkağaç" },
            new City { Id = 622, ProvinceId = 45, Name = "Kula" },
            new City { Id = 623, ProvinceId = 45, Name = "Salihli" },
            new City { Id = 624, ProvinceId = 45, Name = "Sarıgöl" },
            new City { Id = 625, ProvinceId = 45, Name = "Saruhanlı" },
            new City { Id = 626, ProvinceId = 45, Name = "Selendi" },
            new City { Id = 627, ProvinceId = 45, Name = "Soma" },
            new City { Id = 628, ProvinceId = 45, Name = "Turgutlu" },
            new City { Id = 629, ProvinceId = 45, Name = "Ahmetli" },
            new City { Id = 630, ProvinceId = 45, Name = "Gölmarmara" },
            new City { Id = 631, ProvinceId = 45, Name = "Köprübaşı / Manisa" },
            new City { Id = 632, ProvinceId = 45, Name = "Şehzadeler" },
            new City { Id = 633, ProvinceId = 45, Name = "Yunusemre" },
            new City { Id = 634, ProvinceId = 46, Name = "Afşin" },
            new City { Id = 635, ProvinceId = 46, Name = "Andırın" },
            new City { Id = 636, ProvinceId = 46, Name = "Elbistan" },
            new City { Id = 637, ProvinceId = 46, Name = "Göksun" },
            new City { Id = 638, ProvinceId = 46, Name = "Pazarcık" },
            new City { Id = 639, ProvinceId = 46, Name = "Türkoğlu" },
            new City { Id = 640, ProvinceId = 46, Name = "Çağlayancerit" },
            new City { Id = 641, ProvinceId = 46, Name = "Ekinözü" },
            new City { Id = 642, ProvinceId = 46, Name = "Nurhak" },
            new City { Id = 643, ProvinceId = 46, Name = "Dulkadiroğlu" },
            new City { Id = 644, ProvinceId = 46, Name = "Onikişubat" },
            new City { Id = 645, ProvinceId = 47, Name = "Derik" },
            new City { Id = 646, ProvinceId = 47, Name = "Kızıltepe" },
            new City { Id = 647, ProvinceId = 47, Name = "Mazıdağı" },
            new City { Id = 648, ProvinceId = 47, Name = "Midyat" },
            new City { Id = 649, ProvinceId = 47, Name = "Nusaybin" },
            new City { Id = 650, ProvinceId = 47, Name = "Ömerli" },
            new City { Id = 651, ProvinceId = 47, Name = "Savur" },
            new City { Id = 652, ProvinceId = 47, Name = "Dargeçit" },
            new City { Id = 653, ProvinceId = 47, Name = "Yeşilli" },
            new City { Id = 654, ProvinceId = 47, Name = "Artuklu" },
            new City { Id = 655, ProvinceId = 48, Name = "Bodrum" },
            new City { Id = 656, ProvinceId = 48, Name = "Datça" },
            new City { Id = 657, ProvinceId = 48, Name = "Fethiye" },
            new City { Id = 658, ProvinceId = 48, Name = "Köyceğiz" },
            new City { Id = 659, ProvinceId = 48, Name = "Marmaris" },
            new City { Id = 660, ProvinceId = 48, Name = "Milas" },
            new City { Id = 661, ProvinceId = 48, Name = "Ula" },
            new City { Id = 662, ProvinceId = 48, Name = "Yatağan" },
            new City { Id = 663, ProvinceId = 48, Name = "Dalaman" },
            new City { Id = 664, ProvinceId = 48, Name = "Ortaca" },
            new City { Id = 665, ProvinceId = 48, Name = "Kavaklıdere" },
            new City { Id = 666, ProvinceId = 48, Name = "Menteşe" },
            new City { Id = 667, ProvinceId = 48, Name = "Seydikemer" },
            new City { Id = 668, ProvinceId = 49, Name = "Bulanık" },
            new City { Id = 669, ProvinceId = 49, Name = "Malazgirt" },
            new City { Id = 670, ProvinceId = 49, Name = "Muş Merkez" },
            new City { Id = 671, ProvinceId = 49, Name = "Varto" },
            new City { Id = 672, ProvinceId = 49, Name = "Hasköy" },
            new City { Id = 673, ProvinceId = 49, Name = "Korkut" },
            new City { Id = 674, ProvinceId = 50, Name = "Avanos" },
            new City { Id = 675, ProvinceId = 50, Name = "Derinkuyu" },
            new City { Id = 676, ProvinceId = 50, Name = "Gülşehir" },
            new City { Id = 677, ProvinceId = 50, Name = "Hacıbektaş" },
            new City { Id = 678, ProvinceId = 50, Name = "Kozaklı" },
            new City { Id = 679, ProvinceId = 50, Name = "Nevşehir Merkez" },
            new City { Id = 680, ProvinceId = 50, Name = "Ürgüp" },
            new City { Id = 681, ProvinceId = 50, Name = "Acıgöl" },
            new City { Id = 682, ProvinceId = 51, Name = "Bor" },
            new City { Id = 683, ProvinceId = 51, Name = "Çamardı" },
            new City { Id = 684, ProvinceId = 51, Name = "Niğde Merkez" },
            new City { Id = 685, ProvinceId = 51, Name = "Ulukışla" },
            new City { Id = 686, ProvinceId = 51, Name = "Altunhisar" },
            new City { Id = 687, ProvinceId = 51, Name = "Çiftlik" },
            new City { Id = 688, ProvinceId = 52, Name = "Akkuş" },
            new City { Id = 689, ProvinceId = 52, Name = "Aybastı" },
            new City { Id = 690, ProvinceId = 52, Name = "Fatsa" },
            new City { Id = 691, ProvinceId = 52, Name = "Gölköy" },
            new City { Id = 692, ProvinceId = 52, Name = "Korgan" },
            new City { Id = 693, ProvinceId = 52, Name = "Kumru" },
            new City { Id = 694, ProvinceId = 52, Name = "Mesudiye" },
            new City { Id = 695, ProvinceId = 52, Name = "Perşembe" },
            new City { Id = 696, ProvinceId = 52, Name = "Ulubey / Ordu" },
            new City { Id = 697, ProvinceId = 52, Name = "Ünye" },
            new City { Id = 698, ProvinceId = 52, Name = "Gülyalı" },
            new City { Id = 699, ProvinceId = 52, Name = "Gürgentepe" },
            new City { Id = 700, ProvinceId = 52, Name = "Çamaş" },
            new City { Id = 701, ProvinceId = 52, Name = "Çatalpınar" },
            new City { Id = 702, ProvinceId = 52, Name = "Çaybaşı" },
            new City { Id = 703, ProvinceId = 52, Name = "İkizce" },
            new City { Id = 704, ProvinceId = 52, Name = "Kabadüz" },
            new City { Id = 705, ProvinceId = 52, Name = "Kabataş" },
            new City { Id = 706, ProvinceId = 52, Name = "Altınordu" },
            new City { Id = 707, ProvinceId = 53, Name = "Ardeşen" },
            new City { Id = 708, ProvinceId = 53, Name = "Çamlıhemşin" },
            new City { Id = 709, ProvinceId = 53, Name = "Çayeli" },
            new City { Id = 710, ProvinceId = 53, Name = "Fındıklı" },
            new City { Id = 711, ProvinceId = 53, Name = "İkizdere" },
            new City { Id = 712, ProvinceId = 53, Name = "Kalkandere" },
            new City { Id = 713, ProvinceId = 53, Name = "Pazar / Rize" },
            new City { Id = 714, ProvinceId = 53, Name = "Rize Merkez" },
            new City { Id = 715, ProvinceId = 53, Name = "Güneysu" },
            new City { Id = 716, ProvinceId = 53, Name = "Derepazarı" },
            new City { Id = 717, ProvinceId = 53, Name = "Hemşin" },
            new City { Id = 718, ProvinceId = 53, Name = "İyidere" },
            new City { Id = 719, ProvinceId = 54, Name = "Akyazı" },
            new City { Id = 720, ProvinceId = 54, Name = "Geyve" },
            new City { Id = 721, ProvinceId = 54, Name = "Hendek" },
            new City { Id = 722, ProvinceId = 54, Name = "Karasu" },
            new City { Id = 723, ProvinceId = 54, Name = "Kaynarca" },
            new City { Id = 724, ProvinceId = 54, Name = "Sapanca" },
            new City { Id = 725, ProvinceId = 54, Name = "Kocaali" },
            new City { Id = 726, ProvinceId = 54, Name = "Pamukova" },
            new City { Id = 727, ProvinceId = 54, Name = "Taraklı" },
            new City { Id = 728, ProvinceId = 54, Name = "Ferizli" },
            new City { Id = 729, ProvinceId = 54, Name = "Karapürçek" },
            new City { Id = 730, ProvinceId = 54, Name = "Söğütlü" },
            new City { Id = 731, ProvinceId = 54, Name = "Adapazarı" },
            new City { Id = 732, ProvinceId = 54, Name = "Arifiye" },
            new City { Id = 733, ProvinceId = 54, Name = "Erenler" },
            new City { Id = 734, ProvinceId = 54, Name = "Serdivan" },
            new City { Id = 735, ProvinceId = 55, Name = "Alaçam" },
            new City { Id = 736, ProvinceId = 55, Name = "Bafra" },
            new City { Id = 737, ProvinceId = 55, Name = "Çarşamba" },
            new City { Id = 738, ProvinceId = 55, Name = "Havza" },
            new City { Id = 739, ProvinceId = 55, Name = "Kavak" },
            new City { Id = 740, ProvinceId = 55, Name = "Ladik" },
            new City { Id = 741, ProvinceId = 55, Name = "Terme" },
            new City { Id = 742, ProvinceId = 55, Name = "Vezirköprü" },
            new City { Id = 743, ProvinceId = 55, Name = "Asarcık" },
            new City { Id = 744, ProvinceId = 55, Name = "19 Mayıs" },
            new City { Id = 745, ProvinceId = 55, Name = "Salıpazarı" },
            new City { Id = 746, ProvinceId = 55, Name = "Tekkeköy" },
            new City { Id = 747, ProvinceId = 55, Name = "Ayvacık / Samsun" },
            new City { Id = 748, ProvinceId = 55, Name = "Yakakent" },
            new City { Id = 749, ProvinceId = 55, Name = "Atakum" },
            new City { Id = 750, ProvinceId = 55, Name = "Canik" },
            new City { Id = 751, ProvinceId = 55, Name = "İlkadım" },
            new City { Id = 752, ProvinceId = 56, Name = "Baykan" },
            new City { Id = 753, ProvinceId = 56, Name = "Eruh" },
            new City { Id = 754, ProvinceId = 56, Name = "Kurtalan" },
            new City { Id = 755, ProvinceId = 56, Name = "Pervari" },
            new City { Id = 756, ProvinceId = 56, Name = "Siirt Merkez" },
            new City { Id = 757, ProvinceId = 56, Name = "Şirvan" },
            new City { Id = 758, ProvinceId = 56, Name = "Tillo" },
            new City { Id = 759, ProvinceId = 57, Name = "Ayancık" },
            new City { Id = 760, ProvinceId = 57, Name = "Boyabat" },
            new City { Id = 761, ProvinceId = 57, Name = "Durağan" },
            new City { Id = 762, ProvinceId = 57, Name = "Erfelek" },
            new City { Id = 763, ProvinceId = 57, Name = "Gerze" },
            new City { Id = 764, ProvinceId = 57, Name = "Sinop Merkez" },
            new City { Id = 765, ProvinceId = 57, Name = "Türkeli" },
            new City { Id = 766, ProvinceId = 57, Name = "Dikmen" },
            new City { Id = 767, ProvinceId = 57, Name = "Saraydüzü" },
            new City { Id = 768, ProvinceId = 58, Name = "Divriği" },
            new City { Id = 769, ProvinceId = 58, Name = "Gemerek" },
            new City { Id = 770, ProvinceId = 58, Name = "Gürün" },
            new City { Id = 771, ProvinceId = 58, Name = "Hafik" },
            new City { Id = 772, ProvinceId = 58, Name = "İmranlı" },
            new City { Id = 773, ProvinceId = 58, Name = "Kangal" },
            new City { Id = 774, ProvinceId = 58, Name = "Koyulhisar" },
            new City { Id = 775, ProvinceId = 58, Name = "Sivas Merkez" },
            new City { Id = 776, ProvinceId = 58, Name = "Suşehri" },
            new City { Id = 777, ProvinceId = 58, Name = "Şarkışla" },
            new City { Id = 778, ProvinceId = 58, Name = "Yıldızeli" },
            new City { Id = 779, ProvinceId = 58, Name = "Zara" },
            new City { Id = 780, ProvinceId = 58, Name = "Akıncılar" },
            new City { Id = 781, ProvinceId = 58, Name = "Altınyayla / Sivas" },
            new City { Id = 782, ProvinceId = 58, Name = "Doğanşar" },
            new City { Id = 783, ProvinceId = 58, Name = "Gölova" },
            new City { Id = 784, ProvinceId = 58, Name = "Ulaş" },
            new City { Id = 785, ProvinceId = 59, Name = "Çerkezköy" },
            new City { Id = 786, ProvinceId = 59, Name = "Çorlu" },
            new City { Id = 787, ProvinceId = 59, Name = "Hayrabolu" },
            new City { Id = 788, ProvinceId = 59, Name = "Malkara" },
            new City { Id = 789, ProvinceId = 59, Name = "Muratlı" },
            new City { Id = 790, ProvinceId = 59, Name = "Saray / Tekirdağ" },
            new City { Id = 791, ProvinceId = 59, Name = "Şarköy" },
            new City { Id = 792, ProvinceId = 59, Name = "Marmaraereğlisi" },
            new City { Id = 793, ProvinceId = 59, Name = "Ergene" },
            new City { Id = 794, ProvinceId = 59, Name = "Kapaklı" },
            new City { Id = 795, ProvinceId = 59, Name = "Süleymanpaşa" },
            new City { Id = 796, ProvinceId = 60, Name = "Almus" },
            new City { Id = 797, ProvinceId = 60, Name = "Artova" },
            new City { Id = 798, ProvinceId = 60, Name = "Erbaa" },
            new City { Id = 799, ProvinceId = 60, Name = "Niksar" },
            new City { Id = 800, ProvinceId = 60, Name = "Reşadiye" },
            new City { Id = 801, ProvinceId = 60, Name = "Tokat Merkez" },
            new City { Id = 802, ProvinceId = 60, Name = "Turhal" },
            new City { Id = 803, ProvinceId = 60, Name = "Zile" },
            new City { Id = 804, ProvinceId = 60, Name = "Pazar / Tokat" },
            new City { Id = 805, ProvinceId = 60, Name = "Yeşilyurt / Tokat" },
            new City { Id = 806, ProvinceId = 60, Name = "Başçiftlik" },
            new City { Id = 807, ProvinceId = 60, Name = "Sulusaray" },
            new City { Id = 808, ProvinceId = 61, Name = "Akçaabat" },
            new City { Id = 809, ProvinceId = 61, Name = "Araklı" },
            new City { Id = 810, ProvinceId = 61, Name = "Arsin" },
            new City { Id = 811, ProvinceId = 61, Name = "Çaykara" },
            new City { Id = 812, ProvinceId = 61, Name = "Maçka" },
            new City { Id = 813, ProvinceId = 61, Name = "Of" },
            new City { Id = 814, ProvinceId = 61, Name = "Sürmene" },
            new City { Id = 815, ProvinceId = 61, Name = "Tonya" },
            new City { Id = 816, ProvinceId = 61, Name = "Vakfıkebir" },
            new City { Id = 817, ProvinceId = 61, Name = "Yomra" },
            new City { Id = 818, ProvinceId = 61, Name = "Beşikdüzü" },
            new City { Id = 819, ProvinceId = 61, Name = "Şalpazarı" },
            new City { Id = 820, ProvinceId = 61, Name = "Çarşıbaşı" },
            new City { Id = 821, ProvinceId = 61, Name = "Dernekpazarı" },
            new City { Id = 822, ProvinceId = 61, Name = "Düzköy" },
            new City { Id = 823, ProvinceId = 61, Name = "Hayrat" },
            new City { Id = 824, ProvinceId = 61, Name = "Köprübaşı / Trabzon" },
            new City { Id = 825, ProvinceId = 61, Name = "Ortahisar" },
            new City { Id = 826, ProvinceId = 62, Name = "Çemişgezek" },
            new City { Id = 827, ProvinceId = 62, Name = "Hozat" },
            new City { Id = 828, ProvinceId = 62, Name = "Mazgirt" },
            new City { Id = 829, ProvinceId = 62, Name = "Nazımiye" },
            new City { Id = 830, ProvinceId = 62, Name = "Ovacık / Tunceli" },
            new City { Id = 831, ProvinceId = 62, Name = "Pertek" },
            new City { Id = 832, ProvinceId = 62, Name = "Pülümür" },
            new City { Id = 833, ProvinceId = 62, Name = "Tunceli Merkez" },
            new City { Id = 834, ProvinceId = 63, Name = "Akçakale" },
            new City { Id = 835, ProvinceId = 63, Name = "Birecik" },
            new City { Id = 836, ProvinceId = 63, Name = "Bozova" },
            new City { Id = 837, ProvinceId = 63, Name = "Ceylanpınar" },
            new City { Id = 838, ProvinceId = 63, Name = "Halfeti" },
            new City { Id = 839, ProvinceId = 63, Name = "Hilvan" },
            new City { Id = 840, ProvinceId = 63, Name = "Siverek" },
            new City { Id = 841, ProvinceId = 63, Name = "Suruç" },
            new City { Id = 842, ProvinceId = 63, Name = "Viranşehir" },
            new City { Id = 843, ProvinceId = 63, Name = "Harran" },
            new City { Id = 844, ProvinceId = 63, Name = "Eyyübiye" },
            new City { Id = 845, ProvinceId = 63, Name = "Haliliye" },
            new City { Id = 846, ProvinceId = 63, Name = "Karaköprü" },
            new City { Id = 847, ProvinceId = 64, Name = "Banaz" },
            new City { Id = 848, ProvinceId = 64, Name = "Eşme" },
            new City { Id = 849, ProvinceId = 64, Name = "Karahallı" },
            new City { Id = 850, ProvinceId = 64, Name = "Sivaslı" },
            new City { Id = 851, ProvinceId = 64, Name = "Ulubey / Uşak" },
            new City { Id = 852, ProvinceId = 64, Name = "Uşak Merkez" },
            new City { Id = 853, ProvinceId = 65, Name = "Başkale" },
            new City { Id = 854, ProvinceId = 65, Name = "Çatak" },
            new City { Id = 855, ProvinceId = 65, Name = "Erciş" },
            new City { Id = 856, ProvinceId = 65, Name = "Gevaş" },
            new City { Id = 857, ProvinceId = 65, Name = "Gürpınar" },
            new City { Id = 858, ProvinceId = 65, Name = "Muradiye" },
            new City { Id = 859, ProvinceId = 65, Name = "Özalp" },
            new City { Id = 860, ProvinceId = 65, Name = "Bahçesaray" },
            new City { Id = 861, ProvinceId = 65, Name = "Çaldıran" },
            new City { Id = 862, ProvinceId = 65, Name = "Edremit / Van" },
            new City { Id = 863, ProvinceId = 65, Name = "Saray / Van" },
            new City { Id = 864, ProvinceId = 65, Name = "İpekyolu" },
            new City { Id = 865, ProvinceId = 65, Name = "Tuşba" },
            new City { Id = 866, ProvinceId = 66, Name = "Akdağmadeni" },
            new City { Id = 867, ProvinceId = 66, Name = "Boğazlıyan" },
            new City { Id = 868, ProvinceId = 66, Name = "Çayıralan" },
            new City { Id = 869, ProvinceId = 66, Name = "Çekerek" },
            new City { Id = 870, ProvinceId = 66, Name = "Sarıkaya" },
            new City { Id = 871, ProvinceId = 66, Name = "Sorgun" },
            new City { Id = 872, ProvinceId = 66, Name = "Şefaatli" },
            new City { Id = 873, ProvinceId = 66, Name = "Yerköy" },
            new City { Id = 874, ProvinceId = 66, Name = "Yozgat Merkez" },
            new City { Id = 875, ProvinceId = 66, Name = "Aydıncık / Yozgat" },
            new City { Id = 876, ProvinceId = 66, Name = "Çandır" },
            new City { Id = 877, ProvinceId = 66, Name = "Kadışehri" },
            new City { Id = 878, ProvinceId = 66, Name = "Saraykent" },
            new City { Id = 879, ProvinceId = 66, Name = "Yenifakılı" },
            new City { Id = 880, ProvinceId = 67, Name = "Çaycuma" },
            new City { Id = 881, ProvinceId = 67, Name = "Devrek" },
            new City { Id = 882, ProvinceId = 67, Name = "Ereğli / Zonguldak" },
            new City { Id = 883, ProvinceId = 67, Name = "Zonguldak Merkez" },
            new City { Id = 884, ProvinceId = 67, Name = "Alaplı" },
            new City { Id = 885, ProvinceId = 67, Name = "Gökçebey" },
            new City { Id = 886, ProvinceId = 67, Name = "Kilimli" },
            new City { Id = 887, ProvinceId = 67, Name = "Kozlu" },
            new City { Id = 888, ProvinceId = 68, Name = "Aksaray Merkez" },
            new City { Id = 889, ProvinceId = 68, Name = "Ortaköy / Aksaray" },
            new City { Id = 890, ProvinceId = 68, Name = "Ağaçören" },
            new City { Id = 891, ProvinceId = 68, Name = "Güzelyurt" },
            new City { Id = 892, ProvinceId = 68, Name = "Sarıyahşi" },
            new City { Id = 893, ProvinceId = 68, Name = "Eskil" },
            new City { Id = 894, ProvinceId = 68, Name = "Gülağaç" },
            new City { Id = 895, ProvinceId = 69, Name = "Bayburt Merkez" },
            new City { Id = 896, ProvinceId = 69, Name = "Aydıntepe" },
            new City { Id = 897, ProvinceId = 69, Name = "Demirözü" },
            new City { Id = 898, ProvinceId = 70, Name = "Ermenek" },
            new City { Id = 899, ProvinceId = 70, Name = "Karaman Merkez" },
            new City { Id = 900, ProvinceId = 70, Name = "Ayrancı" },
            new City { Id = 901, ProvinceId = 70, Name = "Kazımkarabekir" },
            new City { Id = 902, ProvinceId = 70, Name = "Başyayla" },
            new City { Id = 903, ProvinceId = 70, Name = "Sarıveliler" },
            new City { Id = 904, ProvinceId = 71, Name = "Delice" },
            new City { Id = 905, ProvinceId = 71, Name = "Keskin" },
            new City { Id = 906, ProvinceId = 71, Name = "Kırıkkale Merkez" },
            new City { Id = 907, ProvinceId = 71, Name = "Sulakyurt" },
            new City { Id = 908, ProvinceId = 71, Name = "Bahşili" },
            new City { Id = 909, ProvinceId = 71, Name = "Balışeyh" },
            new City { Id = 910, ProvinceId = 71, Name = "Çelebi" },
            new City { Id = 911, ProvinceId = 71, Name = "Karakeçili" },
            new City { Id = 912, ProvinceId = 71, Name = "Yahşihan" },
            new City { Id = 913, ProvinceId = 72, Name = "Batman Merkez" },
            new City { Id = 914, ProvinceId = 72, Name = "Beşiri" },
            new City { Id = 915, ProvinceId = 72, Name = "Gercüş" },
            new City { Id = 916, ProvinceId = 72, Name = "Kozluk" },
            new City { Id = 917, ProvinceId = 72, Name = "Sason" },
            new City { Id = 918, ProvinceId = 72, Name = "Hasankeyf" },
            new City { Id = 919, ProvinceId = 73, Name = "Beytüşşebap" },
            new City { Id = 920, ProvinceId = 73, Name = "Cizre" },
            new City { Id = 921, ProvinceId = 73, Name = "İdil" },
            new City { Id = 922, ProvinceId = 73, Name = "Silopi" },
            new City { Id = 923, ProvinceId = 73, Name = "Şırnak Merkez" },
            new City { Id = 924, ProvinceId = 73, Name = "Uludere" },
            new City { Id = 925, ProvinceId = 73, Name = "Güçlükonak" },
            new City { Id = 926, ProvinceId = 74, Name = "Bartın Merkez" },
            new City { Id = 927, ProvinceId = 74, Name = "Kurucaşile" },
            new City { Id = 928, ProvinceId = 74, Name = "Ulus" },
            new City { Id = 929, ProvinceId = 74, Name = "Amasra" },
            new City { Id = 930, ProvinceId = 75, Name = "Ardahan Merkez" },
            new City { Id = 931, ProvinceId = 75, Name = "Çıldır" },
            new City { Id = 932, ProvinceId = 75, Name = "Göle" },
            new City { Id = 933, ProvinceId = 75, Name = "Hanak" },
            new City { Id = 934, ProvinceId = 75, Name = "Posof" },
            new City { Id = 935, ProvinceId = 75, Name = "Damal" },
            new City { Id = 936, ProvinceId = 76, Name = "Aralık" },
            new City { Id = 937, ProvinceId = 76, Name = "Iğdır Merkez" },
            new City { Id = 938, ProvinceId = 76, Name = "Tuzluca" },
            new City { Id = 939, ProvinceId = 76, Name = "Karakoyunlu" },
            new City { Id = 940, ProvinceId = 77, Name = "Yalova Merkez" },
            new City { Id = 941, ProvinceId = 77, Name = "Altınova" },
            new City { Id = 942, ProvinceId = 77, Name = "Armutlu" },
            new City { Id = 943, ProvinceId = 77, Name = "Çınarcık" },
            new City { Id = 944, ProvinceId = 77, Name = "Çiftlikköy" },
            new City { Id = 945, ProvinceId = 77, Name = "Termal" },
            new City { Id = 946, ProvinceId = 78, Name = "Eflani" },
            new City { Id = 947, ProvinceId = 78, Name = "Eskipazar" },
            new City { Id = 948, ProvinceId = 78, Name = "Karabük Merkez" },
            new City { Id = 949, ProvinceId = 78, Name = "Ovacık / Karabük" },
            new City { Id = 950, ProvinceId = 78, Name = "Safranbolu" },
            new City { Id = 951, ProvinceId = 78, Name = "Yenice / Karabük" },
            new City { Id = 952, ProvinceId = 79, Name = "Kilis Merkez" },
            new City { Id = 953, ProvinceId = 79, Name = "Elbeyli" },
            new City { Id = 954, ProvinceId = 79, Name = "Musabeyli" },
            new City { Id = 955, ProvinceId = 79, Name = "Polateli" },
            new City { Id = 956, ProvinceId = 80, Name = "Bahçe" },
            new City { Id = 957, ProvinceId = 80, Name = "Kadirli" },
            new City { Id = 958, ProvinceId = 80, Name = "Osmaniye Merkez" },
            new City { Id = 959, ProvinceId = 80, Name = "Düziçi" },
            new City { Id = 960, ProvinceId = 80, Name = "Hasanbeyli" },
            new City { Id = 961, ProvinceId = 80, Name = "Sumbas" },
            new City { Id = 962, ProvinceId = 80, Name = "Toprakkale" },
            new City { Id = 963, ProvinceId = 81, Name = "Akçakoca" },
            new City { Id = 964, ProvinceId = 81, Name = "Düzce Merkez" },
            new City { Id = 965, ProvinceId = 81, Name = "Yığılca" },
            new City { Id = 966, ProvinceId = 81, Name = "Cumayeri" },
            new City { Id = 967, ProvinceId = 81, Name = "Gölyaka" },
            new City { Id = 968, ProvinceId = 81, Name = "Çilimli" },
            new City { Id = 969, ProvinceId = 81, Name = "Gümüşova" },
            new City { Id = 970, ProvinceId = 81, Name = "Kaynaşlı" }
                    );
        }
    }
}
